blog/urls.py
from django.urls import path

from .views import post_detail_view, all_posts_view

app_name = 'blog'

urlpatterns = [
    # Blog
    path('', all_posts_view, name='all_posts_view'),
    path('<slug:post_slug>', post_detail_view, name='post_detail_view'),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include ,re_path
# Mulit Language
from django.utils.translation import gettext_lazy as _
# Media URL ve ROOT tanımı içim
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
# My App
from page.views import home_page_view, contact_page_view, career_page_view

urlpatterns = [
    # Admin    
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += i18n_patterns(
    # Home Page
    path('', home_page_view, name='home_page_view'),
    
    # Contact Page
    path(_('iletisim/'), contact_page_view, name='contact_page_view'),
    path(_('kariyer/'), career_page_view, name='career_page_view'),
    # Page
    path('page/', include('page.urls', namespace='page')),

    # Service
    path('service/', include('service.urls', namespace='service')),

    # Product
    path('product/', include('product.urls', namespace='product')),

)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
]

product/urls.py
from django.urls import path

from .views import product_detail_view, all_products_view

app_name = 'product'

urlpatterns = [
    # Product
    
    path('', all_products_view, name='all_products_view'),
    path('<slug:product_slug>', product_detail_view, name='product_detail_view'),
    # path('<slug:category_slug>', category_view, name='category_view'),
    # path('category/<slug:category_slug>/product/<int:id>/', product_detail_view, name='product_detail_view'),
    # path('', all_products_view, name='all_posts_view'),
    # path('<slug:post_slug>', post_detail_view, name='post_detail_view'),
]

service/urls.py
from django.urls import path
from service.views import firs_service_view
app_name = 'service'

urlpatterns = [
    path('', firs_service_view, name='firs_service_view')
    # path('<slug:page_slug>', single_service_view, name='single_service_view' 
]

templates/core/base.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}{% endblock %} - Elkom Ecza Deposu</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/animate.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/ares.css' %}" rel="stylesheet" />
    <!-- Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;500&display=swap" rel="stylesheet" />
</head>

<body>
    

    {% include 'core/navbar.html' %}

    {% block content %}
    {% endblock content %}

    {% include "core/footer.html" %}

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static '/js/ares.js' %}"></script>

</body>

</html>

templates/core/footer.html
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center pb-4">
                <a class="nav-link" href="#">
                    Bilgi Güvenliği ve Kişisel Verilerin Korunması
                </a>
            </div>
            <div class="col-lg-12 text-center pb-4 fw-light">
                <p>
                    Copyright © 2022 - 2023 Tüm Hakları Saklıdır
                    <span class="text-color-light">Elkom Ecza Deposu</span> |
                    <a href="" class="text-decoration-none"> Elkom Yazılım</a>
                </p>
            </div>
        </div>
    </div>
</footer>

templates/core/messages.html
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong> 
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>        
    {% endfor %}
{% endif %}

{% if form.errors %}
    {% for error in form.errors %}
    <div class="alert alert-danger" role="alert">
        {{error}}
    </div>       
    {% endfor %}
{% endif %}

templates/core/navbar.html
{% load static %}
{% load i18n %}

<nav class="navbar navbar-expand-md navbar-dark border-bottom-nav fixed-top py-4">
    <div class="container-md">
        <a class="navbar-brand" href="{% url 'home_page_view' %}">
            <img src="{% static 'img/logo.png' %}" alt="logo" />
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav ms-auto mb-2 mb-md-0 mt-4 mt-md-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home_page_view' %}">{{ _('Ana Sayfa') }}</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" data-bs-toggle="dropdown" aria-expanded="false">{{ _('Kurumsal') }}</a>
                    <ul class="dropdown-menu">
                        {% for page in global_pages_context %}
                            <li><a class="dropdown-item" href="{{ page.get_absolute_url }}">{{ page.title }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'service:firs_service_view' %}">{{ _('Hizmetlerimiz') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'product:all_products_view' %}">{{ _('Ürün Gruplarımız') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">{{ _('Habeler') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'career_page_view' %}">{{ _('Kariyer') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contact_page_view' %}">{{ _('İletişim') }}</a>
                </li>
                <li class="nav-item">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for lan in languages %}
                        {% if lan.code != LANGUAGE_CODE %}
                        <a class="nav-link" href="/{{lan.code}}">{{lan.name_local}}</a>
                        {% endif %}
                    {% endfor %}
                </li>
            </ul>
        </div>
    </div>
</nav>